import type { ReactNode } from "react";
import { BenchmarkMini } from "./BenchmarkMini";

/**
 * The stage's script: one entry per scroll beat, index 0 being the hero.
 *
 * The panel opens blank — grid only — and the landscape arrives with
 * chapter 01. From there a single response surface stays put for all
 * four beats and each beat lays an OVERLAY on it. The four chapters are
 * one object being reinterpreted, not four pictures, which is what lets
 * the change between them be a wipe rather than a crossfade between
 * unrelated images. The hero drawing returns at the end, sliding in as
 * the box opens.
 *
 * Artwork is generated by `scripts/build-scenes.py` — it is build
 * output, not hand-edited. Everything is a plain <img>: the glass
 * renderer composites direct-child media through drawImage, while
 * anything else goes through html-to-image on every change.
 */

export type Beat = {
  id: string;
  /**
   * The landscape only appears for beats that overlay something on it —
   * mounting is what gates it, so a beat with no overlay is a bare field.
   */
  overlay: string | null;
  /** Null where the beat carries no glass readout. */
  readout: ReactNode | null;
  /** Card stack, for beats that break the argument into pieces instead. */
  cards?: Card[];
  /** Stages walked one at a time while the beat's copy is pinned. */
  stages?: Stage[];
};

export type Stage = {
  name: string;
  body: string;
};

/** Clockwise from the top of the ring, matching the Trellis loop. */
export const LOOP_STAGES: Stage[] = [
  { name: "Frame", body: "Define the objective, responses, factors and constraints." },
  { name: "Design", body: "Design the experiments that add useful evidence." },
  { name: "Integrate", body: "Structure process, experimental and analytical data." },
  { name: "Model", body: "Learn process behaviour from everything accumulated so far." },
  { name: "Optimize", body: "Identify high-performing, robust operating regions." },
  { name: "Learn", body: "Identify the next best experiment to run." },
];

export type Card = {
  n: string;
  kicker: string;
  heading: string;
  body: string;
  figure: ReactNode;
};

/* The three figures are drawn at 132×84 and share one faint plotting
   grid, so the cards read as three readings of the same space. */

const FigGrid = () => (
  <g stroke="currentColor" strokeOpacity={0.16} strokeWidth={1}>
    {[0, 1, 2, 3, 4, 5, 6].map((i) => (
      <line key={`v${i}`} x1={6 + i * 20} y1={6} x2={6 + i * 20} y2={78} />
    ))}
    {[0, 1, 2, 3, 4].map((i) => (
      <line key={`h${i}`} x1={6} y1={6 + i * 18} x2={126} y2={6 + i * 18} />
    ))}
  </g>
);

const FigScarce = () => (
  <svg viewBox="0 0 132 84" className="h-[84px] w-[132px] text-paper" aria-hidden>
    <FigGrid />
    {[[26, 62], [66, 42], [106, 24]].map(([x, y]) => (
      <circle key={x} cx={x} cy={y} r={4.5} fill="currentColor" />
    ))}
  </svg>
);

const FigInteracting = () => {
  const nodes = [[30, 58], [66, 26], [96, 62], [116, 40]];
  return (
    <svg viewBox="0 0 132 84" className="h-[84px] w-[132px] text-paper" aria-hidden>
      <FigGrid />
      <g stroke="currentColor" strokeOpacity={0.5} strokeWidth={1.2}>
        <line x1={30} y1={58} x2={66} y2={26} />
        <line x1={66} y1={26} x2={96} y2={62} />
        <line x1={66} y1={26} x2={116} y2={40} />
        <line x1={30} y1={58} x2={96} y2={62} />
      </g>
      {nodes.map(([x, y]) => (
        <circle
          key={`${x}-${y}`}
          cx={x}
          cy={y}
          r={5.5}
          fill="none"
          stroke="currentColor"
          strokeOpacity={0.9}
          strokeWidth={1.8}
        />
      ))}
    </svg>
  );
};

const FigFragmented = () => (
  <svg viewBox="0 0 132 84" className="h-[84px] w-[132px] text-paper" aria-hidden>
    {[
      ["DESIGN", 4, 6],
      ["DATA", 70, 6],
      ["MODEL", 4, 46],
      ["DECISION", 70, 46],
    ].map(([label, x, y]) => (
      <g key={label as string}>
        <rect
          x={x as number}
          y={y as number}
          width={58}
          height={32}
          rx={4}
          fill="none"
          stroke="currentColor"
          strokeOpacity={0.34}
          strokeWidth={1}
        />
        <text
          x={(x as number) + 29}
          y={(y as number) + 20}
          textAnchor="middle"
          fill="currentColor"
          fillOpacity={0.62}
          fontSize={8}
          letterSpacing="0.12em"
        >
          {label}
        </text>
      </g>
    ))}
  </svg>
);

export const PROBLEM_CARDS: Card[] = [
  {
    n: "01",
    kicker: "Limited experiments",
    heading: "Physical experimentation is scarce.",
    body: "The design space is far larger than the laboratory can physically sample.",
    figure: <FigScarce />,
  },
  {
    n: "02",
    kicker: "Interacting variables",
    heading: "Parameters affect one another.",
    body: "Understanding one variable in isolation rarely explains the process.",
    figure: <FigInteracting />,
  },
  {
    n: "03",
    kicker: "Fragmented learning",
    heading: "Context breaks between tools.",
    body: "Design, evidence, assumptions, models and decisions end up in different systems — or different people.",
    figure: <FigFragmented />,
  },
];

const Readout = ({
  label,
  stat,
  line,
  children,
}: {
  label: string;
  stat?: string;
  line: string;
  children?: ReactNode;
}) => (
  <div className="flex flex-col gap-3">
    <span className="text-[0.625rem] font-medium uppercase tracking-[0.28em] text-paper/60">
      {label}
    </span>
    {stat ? (
      <span className="text-[1.5rem] font-semibold leading-none tracking-[-0.02em] text-paper">
        {stat}
      </span>
    ) : null}
    {children}
    <span className="text-[0.8125rem] leading-snug text-paper/70">{line}</span>
  </div>
);

export const BEATS: Beat[] = [
  {
    id: "hero",
    overlay: null,
    readout: null,
  },
  {
    id: "problem",
    overlay: null,
    readout: null,
    cards: PROBLEM_CARDS,
  },
  {
    id: "loop",
    overlay: "/illustration/overlay-loop.svg",
    readout: null,
    stages: LOOP_STAGES,
  },
  {
    id: "evidence",
    overlay: "/illustration/overlay-evidence.svg",
    readout: (
      <Readout
        label="03 · The evidence"
        line="Trellis 99% · DoE 77% · OFAT 50% of the known optimum titre."
      >
        <div className="py-1">
          <BenchmarkMini />
        </div>
      </Readout>
    ),
  },
];

export type Chapter = {
  step: string;
  kicker: string;
  heading: ReactNode;
  body: string[];
};

/** Chapters map onto beats 1–4; the hero occupies beat 0. */
export const CHAPTERS: Chapter[] = [
  {
    step: "01",
    kicker: "The problem",
    heading: (
      <>
        You are optimising a process you can only{" "}
        <em className="not-italic text-ink-500">partially observe</em>.
      </>
    ),
    body: [
      "From a limited number of experiments you still have to work out which parameters matter, how they interact, what drives your CQAs, and where the process is robust.",
      "Most of the design space will never be tested. So a condition that looks good may simply be the best one you happened to sample.",
    ],
  },
  {
    step: "02",
    kicker: "How it works",
    heading: (
      <>
        A learning loop the{" "}
        <em className="not-italic text-ink-500">scientist</em> drives.
      </>
    ),
    body: [
      "Trellis connects experiment design, data, modelling and next-experiment selection into one continuous workflow — then recommends the run most likely to produce evidence that matters for the next decision.",
      "You define the objective, factors and constraints, review what the model has learned, and decide whether it needs refining before the next experiment runs.",
    ],
  },
  {
    step: "03",
    kicker: "The evidence",
    heading: (
      <>
        Same process, same objective,{" "}
        <em className="not-italic text-ink-500">different</em> learning
        efficiency.
      </>
    ),
    body: [
      "OFAT, DoE and Trellis were benchmarked on the same virtual 12-factor CHO fed-batch process. Trellis reached effectively the full known optimum; DoE plateaued near 77%, OFAT near 50%.",
      "The difference is where the experiments go. OFAT searches locally, DoE spreads broadly and wastes runs far from the optimum, Trellis explores uncertain regions and concentrates where better performance is most likely.",
    ],
  },
];

export const CLOSING_STEPS = [
  {
    n: "01",
    title: "Bring one process",
    body: "A live process with an important, unresolved question.",
  },
  {
    n: "02",
    title: "Define the objective",
    body: "Agree the objective, available evidence, practical experiments and success measures.",
  },
  {
    n: "03",
    title: "Run a focused pilot",
    body: "Configure Trellis, generate new evidence, review what the model learns, decide next steps.",
  },
];
