import type { CSSProperties, ReactNode } from "react";
import { BENCHMARK, BENCHMARK_LEAD } from "@/lib/stage/benchmark";

/**
 * The stage's script: one entry per scroll beat, index 0 being the hero.
 *
 * The panel opens blank — grid only — and the landscape arrives with
 * chapter 01. From there a single response surface stays put for all
 * four beats and each beat lays an OVERLAY on it. The four chapters are
 * one object being reinterpreted, not four pictures, which is what lets
 * the change between them be a wipe rather than a crossfade between
 * unrelated images. The hero drawing returns at the end, sliding in as
 * the box opens.
 *
 * Artwork is generated by `scripts/build-scenes.py` — it is build
 * output, not hand-edited. Everything is a plain <img>: the glass
 * renderer composites direct-child media through drawImage, while
 * anything else goes through html-to-image on every change.
 */

export type Beat = {
  id: string;
  /**
   * The landscape only appears for beats that overlay something on it —
   * mounting is what gates it, so a beat with no overlay is a bare field.
   */
  overlay: string | null;
  /** Plots the benchmark chart on the board. */
  chart?: boolean;
  /** Card stack, for beats that break the argument into pieces instead. */
  cards?: Card[];
  /** Stages walked one at a time while the beat's copy is pinned. */
  stages?: Stage[];
};

export type Stage = {
  name: string;
  body: string;
};

/** Clockwise from the top of the ring, matching the Trellis loop. */
export const LOOP_STAGES: Stage[] = [
  { name: "Frame", body: "Define the objective, responses, factors and constraints." },
  { name: "Design", body: "Design the experiments that add useful evidence." },
  { name: "Integrate", body: "Structure process, experimental and analytical data." },
  { name: "Model", body: "Learn process behaviour from everything accumulated so far." },
  { name: "Optimize", body: "Identify high-performing, robust operating regions." },
  { name: "Learn", body: "Identify the next best experiment to run." },
];

export type Card = {
  kicker: string;
  body: string;
  figure: ReactNode;
};

/* The three figures are drawn at 132×84 and share one faint plotting
   grid, so the cards read as three readings of the same space. */

const FigGrid = () => (
  <g stroke="currentColor" strokeOpacity={0.3} strokeWidth={1}>
    {[0, 1, 2, 3, 4, 5, 6].map((i) => (
      <line key={`v${i}`} x1={6 + i * 20} y1={6} x2={6 + i * 20} y2={78} />
    ))}
    {[0, 1, 2, 3, 4].map((i) => (
      <line key={`h${i}`} x1={6} y1={6 + i * 18} x2={126} y2={6 + i * 18} />
    ))}
  </g>
);

const FigScarce = () => (
  <svg viewBox="0 0 132 84" className="h-[84px] w-[132px] text-paper" aria-hidden>
    <FigGrid />
    {[[26, 62], [66, 42], [106, 24]].map(([x, y]) => (
      <circle key={x} cx={x} cy={y} r={4.5} fill="currentColor" />
    ))}
  </svg>
);

const FigInteracting = () => {
  const nodes = [[30, 58], [66, 26], [96, 62], [116, 40]];
  return (
    <svg viewBox="0 0 132 84" className="h-[84px] w-[132px] text-paper" aria-hidden>
      <FigGrid />
      <g stroke="currentColor" strokeOpacity={0.75} strokeWidth={1.3}>
        <line x1={30} y1={58} x2={66} y2={26} />
        <line x1={66} y1={26} x2={96} y2={62} />
        <line x1={66} y1={26} x2={116} y2={40} />
        <line x1={30} y1={58} x2={96} y2={62} />
      </g>
      {nodes.map(([x, y]) => (
        <circle
          key={`${x}-${y}`}
          cx={x}
          cy={y}
          r={5.5}
          fill="none"
          stroke="currentColor"
          strokeOpacity={0.9}
          strokeWidth={1.8}
        />
      ))}
    </svg>
  );
};

const FigFragmented = () => (
  <svg viewBox="0 0 132 84" className="h-[84px] w-[132px] text-paper" aria-hidden>
    {[
      ["DESIGN", 4, 6],
      ["DATA", 70, 6],
      ["MODEL", 4, 46],
      ["DECISION", 70, 46],
    ].map(([label, x, y]) => (
      <g key={label as string}>
        <rect
          x={x as number}
          y={y as number}
          width={58}
          height={32}
          rx={4}
          fill="none"
          stroke="currentColor"
          strokeOpacity={0.55}
          strokeWidth={1.1}
        />
        <text
          x={(x as number) + 29}
          y={(y as number) + 20}
          textAnchor="middle"
          fill="currentColor"
          fillOpacity={0.85}
          fontSize={8}
          letterSpacing="0.12em"
        >
          {label}
        </text>
      </g>
    ))}
  </svg>
);

export const PROBLEM_CARDS: Card[] = [
  {
    kicker: "Limited experiments",
    body: "The design space is far larger than the laboratory can physically sample.",
    figure: <FigScarce />,
  },
  {
    kicker: "Interacting variables",
    body: "Understanding one variable in isolation rarely explains the process.",
    figure: <FigInteracting />,
  },
  {
    kicker: "Fragmented learning",
    body: "Design, evidence, assumptions, models and decisions end up in different systems — or different people.",
    figure: <FigFragmented />,
  },
];

export const BEATS: Beat[] = [
  {
    // The hero drawing is mounted by Stage.tsx directly, not through the
    // beat's overlay slot: it leaves on scroll rather than on the beat.
    id: "hero",
    overlay: null,
  },
  {
    id: "problem",
    overlay: null,
    cards: PROBLEM_CARDS,
  },
  {
    // No artwork at all: the board is bare for this beat and the loop
    // diagram (DOM + inline SVG, so it can reveal against scroll) is
    // what draws on it. `overlay: null` is also what keeps the shared
    // response surface from mounting underneath.
    id: "loop",
    overlay: null,
    stages: LOOP_STAGES,
  },
  {
    // Nothing but the plot. `overlay: null` is what keeps both the
    // evidence overlay and the shared response surface from mounting.
    id: "evidence",
    overlay: null,
    chart: true,
  },
];

/**
 * The benchmark as three enlarged figures.
 *
 * Ascending, so read left to right the row IS the climb, and the lead
 * strategy carries the weight — same size as the others so the numbers
 * stay comparable, but full ink against their grey. Sizing the winner
 * larger would flatter the comparison rather than making it.
 */
const BenchmarkFigures = () => (
  <dl className="benchmark-figures">
    {BENCHMARK.map((series, i) => (
      <div key={series.name} data-lead={i === BENCHMARK_LEAD}>
        <dt>{series.name}</dt>
        <dd>
          {series.value}
          <span>%</span>
        </dd>
      </div>
    ))}
  </dl>
);

/**
 * The hero's annotation loop — the three stages the drawing runs
 * through, one on screen at a time.
 *
 * Every coordinate here is a fraction of the ARTWORK's own box, not the
 * panel's: the drawing is sized in `vw` and the panel in `vw` × `vh`, so
 * its vertical position inside the panel moves with the viewport shape.
 * Anchored to the art box instead, a leader line lands on its vessel at
 * any window size. `.stage-notes` is given that exact box, and the
 * leaders' <svg> shares the drawing's 1663×870 viewBox.
 *
 * `to` was measured off the drawing rather than guessed — the alpha
 * centroid of each vessel in `path-light.png`.
 *
 * The cards are held well clear of their anchors so each leader has room
 * to be a line rather than a tick, and each `from` sits exactly on the
 * card edge it leaves. That is also why `.stage-note` is sized as a
 * plain per-cent of the art box and not capped in rem: a card whose
 * width stopped tracking the box would pull away from its own line.
 */
export type HeroNote = {
  kicker: string;
  body: string;
  /**
   * Card placement inside the art box, written so the edge the leader
   * leaves from is the edge that is PINNED. The card's height is set by
   * its text, in px, so its top and bottom cannot both be known in art
   * box per-cent — pin the one the line touches and the join is exact at
   * every viewport, whatever the copy wraps to.
   */
  place: CSSProperties;
  /** Where the leader leaves the card, and the vessel it lands on. */
  from: [number, number];
  to: [number, number];
};

export const HERO_NOTES: HeroNote[] = [
  {
    kicker: "Plate",
    body: "High-throughput screening — many conditions sampled at once.",
    // Leaves the bottom edge, so the bottom edge is what is pinned.
    place: { left: "0%", bottom: "56%" },
    from: [0.111, 0.44],
    to: [0.111, 0.88],
  },
  {
    kicker: "Bench → Pilot",
    body: "Trellis narrows toward the conditions worth carrying forward.",
    // The only one that reaches UP: it sits below its vessel and the
    // leader runs back to it, so the card's TOP edge is what is pinned.
    // It hangs below the art box, on the bare board — which is fine,
    // the panel is the canvas — but not unboundedly: the art box is
    // width-bound while the panel tracks viewport HEIGHT, so a short
    // window closes in on it. The binding case is wide-and-short (the art
    // box is nearly as tall as the panel there); 106% with a two-line
    // card still clears 1920×760, and lower starts clipping.
    // Wider than the others on purpose: at 56% the sentence wraps to two
    // lines instead of three, which is ~25px less card. That is what buys
    // the extra drop below — see the clipping note.
    place: { left: "14%", top: "106%", width: "56%" },
    from: [0.395, 1.06],
    to: [0.395, 0.691],
  },
  {
    kicker: "Production",
    body: "The process arrives de-risked, its true potential established.",
    // Reaches ACROSS rather than down: this vessel's anchor sits high in
    // the drawing, so there is no room for a card above it. The right
    // edge is pinned by `left` + the card's fixed 46% width, and
    // `translate` centres the card on the point the line leaves from —
    // `translate` rather than `transform`, which the loop keyframes own.
    // Sitting above the vessel, the leader runs slightly downhill into
    // it rather than dead level.
    place: { left: "19%", top: "26%", translate: "0 -50%" },
    from: [0.65, 0.26],
    to: [0.895, 0.337],
  },
];

export type Chapter = {
  kicker: string;
  heading: ReactNode;
  body: string[];
  /** Extra content under the copy — the benchmark figures, so far. */
  aside?: ReactNode;
};

/** Chapters map onto beats 1–4; the hero occupies beat 0. */
export const CHAPTERS: Chapter[] = [
  {
    kicker: "The problem",
    heading: (
      <>
        You are optimising a process you can only{" "}
        <em className="not-italic text-ink-500">partially observe</em>.
      </>
    ),
    body: [
      "From a limited number of experiments you still have to work out which parameters matter, how they interact, what drives your CQAs, and where the process is robust.",
      "Most of the design space will never be tested. So a condition that looks good may simply be the best one you happened to sample.",
    ],
  },
  {
    kicker: "How it works",
    heading: (
      <>
        A learning loop the{" "}
        <em className="not-italic text-ink-500">scientist</em> drives.
      </>
    ),
    body: [
      "Trellis connects experiment design, data, modelling and next-experiment selection into one continuous workflow — then recommends the run most likely to produce evidence that matters for the next decision.",
      "You define the objective, factors and constraints, review what the model has learned, and decide whether it needs refining before the next experiment runs.",
    ],
  },
  {
    kicker: "The evidence",
    heading: (
      <>
        Same process, same objective,{" "}
        <em className="not-italic text-ink-500">different</em> learning
        efficiency.
      </>
    ),
    body: [
      "OFAT, DoE and Trellis were benchmarked on the same virtual 12-factor CHO fed-batch process. Trellis reached effectively the full known optimum; DoE plateaued near 77%, OFAT near 50%.",
      "The difference is where the experiments go. OFAT searches locally, DoE spreads broadly and wastes runs far from the optimum, Trellis explores uncertain regions and concentrates where better performance is most likely.",
    ],
    aside: <BenchmarkFigures />,
  },
];

export const CLOSING_STEPS = [
  {
    n: "01",
    title: "Bring one process",
    body: "A live process with an important, unresolved question.",
  },
  {
    n: "02",
    title: "Define the objective",
    body: "Agree the objective, available evidence, practical experiments and success measures.",
  },
  {
    n: "03",
    title: "Run a focused pilot",
    body: "Configure Trellis, generate new evidence, review what the model learns, decide next steps.",
  },
];
